# Generated by Django 2.2.8 on 2024-12-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='news',
            name='view_count',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.CharField(default='default_tag', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterModelTable(
            name='news',
            table='EditorPicks',
        ),
    ]
